[postgres]
    host = "localhost"
    port = 5432
    user = "root"
    pass= "root"
    dbname = "postgres"

[redis]
    host = "localhost"
    port = 6379

[mongo]
    host = "localhost"
    port = 27017
    user = "root"
    pass = "root"

[server]
    port = ":8080"

[jwt]
    secret = "secret"