[database]
    host = "localhost"
    port = 5432
    user = "root"
    pass= "root"
    dbname = "postgres"

[redis]
    host = "localhost"
    port = 6379

[server]
    port = ":8080"

[jwt]
    secret = "secret"